name: Build Catalog

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      excel_path:
        description: 'Excel path (default: data/RESUMEN_CATALOGO.xlsx)'
        required: false
        default: 'data/RESUMEN_CATALOGO.xlsx'
  push:
    paths:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CSE_KEY: ${{ secrets.GOOGLE_CSE_KEY }}
      GOOGLE_CSE_CX:  ${{ secrets.GOOGLE_CSE_CX }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      # Pre-chequeo (no imprime los valores, solo confirma que existen)
      - name: Check required secrets
        run: |
          if [ -z "${GOOGLE_CSE_KEY}" ]; then echo "ERROR: GOOGLE_CSE_KEY is missing"; exit 1; fi
          if [ -z "${GOOGLE_CSE_CX}" ]; then echo "ERROR: GOOGLE_CSE_CX is missing"; exit 1; fi
          echo "OK: both secrets are present"

      - name: Enrich URLs
        run: |
          python scripts/enrich_urls.py \
            --excel "${{ github.event.inputs.excel_path || 'data/RESUMEN_CATALOGO.xlsx' }}" \
            --out   "data/RESUMEN_CATALOGO_READY.xlsx" \
            --report "data/ENRICHMENT_REPORT.csv"

      - name: Upload enriched Excel (for debug)
        uses: actions/upload-artifact@v4
        with:
          name: RESUMEN_CATALOGO_READY
          path: data/RESUMEN_CATALOGO_READY.xlsx

      - name: Upload enrichment report (for debug)
        uses: actions/upload-artifact@v4
        with:
          name: ENRICHMENT_REPORT
          path: data/ENRICHMENT_REPORT.csv

      - name: Run downloader
        run: python scripts/download_catalog.py --excel "data/RESUMEN_CATALOGO_READY.xlsx"

      - name: Upload artifact (CATALOGO.zip)
        uses: actions/upload-artifact@v4
        with:
          name: CATALOGO_ZIP
          path: CATALOGO.zip

      - name: Commit output folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A output || true
          git commit -m "Output catalog $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push
