name: Build Catalog

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      excel_path:
        description: 'Excel path (default: data/RESUMEN_CATALOGO.xlsx)'
        required: false
        default: 'data/RESUMEN_CATALOGO.xlsx'
  push:
    paths:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      # Enrich: find official image + PDF and write RESUMEN_CATALOGO_READY.xlsx
      - name: Enrich URLs
        run: |
          python scripts/enrich_urls.py --excel "${{ github.event.inputs.excel_path || 'data/RESUMEN_CATALOGO.xlsx' }}" --out "data/RESUMEN_CATALOGO_READY.xlsx"

      # Upload the enriched Excel so you can inspect what was found
      - name: Upload enriched Excel (for debug)
        uses: actions/upload-artifact@v4
        with:
          name: RESUMEN_CATALOGO_READY
          path: data/RESUMEN_CATALOGO_READY.xlsx

      # Download using the enriched file
      - name: Run downloader
        run: python scripts/download_catalog.py --excel "data/RESUMEN_CATALOGO_READY.xlsx"

      - name: Upload artifact (CATALOGO.zip)
        uses: actions/upload-artifact@v4
        with:
          name: CATALOGO_ZIP
          path: CATALOGO.zip

      # Optional: commit browsable output/ tree back to the repo
      - name: Commit output folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A output || true
          git commit -m "Output catalog $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push
