name: Build Catalog

on:
  workflow_dispatch:
    inputs:
      excel_path:
        description: 'Excel path (default: data/RESUMEN_CATALOGO.xlsx)'
        required: false
        default: 'data/RESUMEN_CATALOGO.xlsx'
  push:
    paths:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run downloader
        run: python scripts/download_catalog.py --excel "${{ github.event.inputs.excel_path || 'data/RESUMEN_CATALOGO.xlsx' }}"

      - name: Upload artifact (CATALOGO.zip)
        uses: actions/upload-artifact@v4
        with:
          name: CATALOGO_ZIP
          path: CATALOGO.zip

      - name: Commit output folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output || true
          git commit -m "Output catalog $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push
